### ISSUE TITLE
Add a flag to similarity.py -J that omits TIka extraction and uses existing JSON

### ISSUE THREAD

**Issue by chrismattmann** [chrismattmann/tika-similarity#65]

**Comment by fysteven** [comment]
@chrismattmann Hey Professor, I've added a flag and basically, it's working for me. It needs a pre-processing before running similarity score. Would you like to update it some time?

**Comment by chrismattmann** [comment]
yes @fysteven please send a pull request thanks!

**Comment by chrismattmann** [comment]
hey @fysteven do you have time to send this patch?

**Comment by chrismattmann** [comment]
ping @fysteven Frank do you have time to send me your PR on this?

**Comment by fysteven** [comment]
Sorry, professor. It's been a year since I worked on this last time. I don't even remember if I still have this in my repo. Maybe what you want is in this commit? https://github.com/fysteven/tika-similarity/commit/624bd504018a7ec9e3320c2cd10238c1ddfe4e58
Let me know if that's it, I will submit a PR. Or if it's something else, I need to look for it on my computer and see if it's there.

**Comment by chrismattmann** [comment]
awesome thanks @fysteven yes I think that's the commit I was looking for. If you time please send a PR or I will figure out how to do it thanks!

**Comment by fysteven** [comment]
A PR has been sent. @chrismattmann It seems I have a separate function there to not mess up with the original function. Sorry, I really should have done this last year. Since I don't remember much about how to use the script, please take a look at the change and verify or have some of your students verify it serves the purpose. Let me know if you need more help.

**Comment by chrismattmann** [comment]
closed in #82

**Comment by chrismattmann** [comment]
thanks @fysteven !
